### ISSUE TITLE
When disable fps limit, server bar info refreshes too quickly to read the value

### ISSUE THREAD

**Issue by yjywybb** [MidoriKami/ChillFrames#14]
It is grateful if you can make it refresh more slowly, such as once per second.

https://github.com/MidoriKami/ChillFrames/assets/18324677/1c1d6741-60c5-41b6-a20c-bb3c71db7d5a

**Comment by MidoriKami** [comment]
It's not an average fps display it is a immediate fps display. If you need an average fps display use FPSPlugin by Caraxi.

**Comment by Theletha** [comment]
> It's not an average fps display it is a immediate fps display. If you need an average fps display use FPSPlugin by Caraxi.

why cant it just lower the polling speed? i like the ability to disable the fps lock on the click of the fps meter. now i have 2 fps meters at the top lol

**Comment by MidoriKami** [comment]
If your framerate is that unstable, you should strongly consider adjusting your graphics settings, as high variance in framerate is the key contributor to not having a smooth gameplay experience.

And I'll reiterate, the ChillFrames FPS display is designed to show you the framerate that it has calculated and determined in its calculations. It allows you to diagnose and resolve issues that a averaged out FPS display simply can not help you with.

I have no intention of ever changing this behavior.

**Comment by yjywybb** [comment]
Why not consider to add an option to show average value?

**Comment by Theletha** [comment]
> If your framerate is that unstable, you should strongly consider adjusting your graphics settings, as high variance in framerate is the key contributor to not having a smooth gameplay experience.
> 
> And I'll reiterate, the ChillFrames FPS display is designed to show you the framerate that it has calculated and determined in its calculations. It allows you to diagnose and resolve issues that a averaged out FPS display simply can not help you with.
> 
> I have no intention of ever changing this behavior.

I dont know why you're hung up on an average value. Lowering the polling rate won't really make it an average instead just more readable on fluctuations and you know you can make this as another option and not the only option. I'm on a 4090 so when i have the cap on 237fps it goes up and down a lot the gameplay is fine but yeah the fps meter is not having a good time.

**Comment by Yveldi** [comment]
You MUST be playing on a capped framerate if you think the current behavior is useful. It is literally impossible to read the FPS value. All I can tell is that, when I enable ReShade, it sometimes dips below 100, and it doesn't do that when I do not use it. I cannot even tell how often it dips below 100 because I am fairly sure the number changes over 100 times every second. Are you superhuman? What use are you getting out of this?

I would be more than happy to use another FPS counter but then I have to go to your mod's settings menu every time to enable/disable it, and clicking the top right is infinitely more convenient. At least give us an option to turn it into a square or something, so we are not forced to have this FPS counter enabled as the only method for convenience. 

I use this mod exclusively for when I am leaving the game running when I work, so that my PC fans will chill, so toggling it on and off is the only use I get out of it personally. I would argue this is a valid use-case, because why would you limit it out when you could easily make it useable for that purpose? However, when I use it for that purpose, I *need* the FPS counter for ease of use (otherwise I might as well use RTSS), and it is quite frustrating that this mod makes all of my other information at the top right move left-right-left-right tens of times every second. I have disabled all the other mods with a "Server Info" feature as a temporary solution, but at this rate I might just learn how to program just so I can have a mod that is compatible with other mods.

**Comment by Theletha** [comment]
> You MUST be playing on a capped framerate if you think the current behavior is useful. It is literally impossible to read the FPS value. All I can tell is that, when I enable ReShade, it sometimes dips below 100, and it doesn't do that when I do not use it. I cannot even tell how often it dips below 100 because I am fairly sure the number changes over 100 times every second. Are you superhuman? What use are you getting out of this?
> 
> I would be more than happy to use another FPS counter but then I have to go to your mod's settings menu every time to enable/disable it, and clicking the top right is infinitely more convenient. At least give us an option to turn it into a square or something, so we are not forced to have this FPS counter enabled as the only method for convenience.
> 
> I use this mod exclusively for when I am leaving the game running when I work, so that my PC fans will chill, so toggling it on and off is the only use I get out of it personally. I would argue this is a valid use-case, because why would you limit it out when you could easily make it useable for that purpose? However, when I use it for that purpose, I _need_ the FPS counter for ease of use (otherwise I might as well use RTSS), and it is quite frustrating that this mod makes all of my other information at the top right move left-right-left-right tens of times every second. I have disabled all the other mods with a "Server Info" feature as a temporary solution, but at this rate I might just learn how to program just so I can have a mod that is compatible with other mods.

i turned his fps meter off and used the one from hazel tweaks instead it has a normal fps meter in the server info bar.
